# RocketMQ Topic 配置
# 领域事件相关 Topic
rocketmq.topic.admin-event=TOPIC_ADMIN_EVENT
rocketmq.topic.user-action=TOPIC_USER_ACTION
rocketmq.topic.content-event=TOPIC_CONTENT_EVENT
rocketmq.topic.social-event=TOPIC_SOCIAL_EVENT
